name: CI

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js 14
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Setup cache
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: npm install
        run: |
          npm ci

      - name: Lint
        run: |
          npm run lint

  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: ['12', '14', '16']
        mocha-version: ['6', '7', '8']
        include:
          - os: ubuntu-latest
            node-version: '14'
            mocha-version: '8'
            coverage: true

    name: 'Test, node: ${{ matrix.node-version }} mocha: ${{ matrix.mocha-version }} coverage: ${{ matrix.coverage }}}'

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Setup cache
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-mocha${{ matrix.mocha-version }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-mocha${{ matrix.mocha-version }}-

      - name: npm install
        run: |
          npm ci
          npm install mocha@${{ matrix.mocha-version }}

      - name: test
        run: |
          npm run test

      - name: Generate Coverage Report
        if: ${{ matrix.coverage }}
        run: npm run coverage-report-lcov

      - name: Upload Coverage to Coveralls
        if: ${{ matrix.coverage }}
        uses: coverallsapp/github-action@master
        with:
          github-token: '${{ secrets.GITHUB_TOKEN }}'

      - name: Upload Coverage to Codecov
        if: ${{ matrix.coverage }}
        uses: codecov/codecov-action@v1
        with:
          fail_ci_if_error: true
